#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
@Project: doxy-to-godot
@Date: 5/25/26
@File: doxy_build_profile

@Author: Silenuz Nowan (silenuznowan@Yahoo.com)

python script to create a build_profile.json file from doxygen XML output
"""
import sys
import json
import re
from collections import namedtuple
from pathlib import Path
from xml.etree import ElementTree as et

xml_input_folder = sys.argv[1]
dest_folder = sys.argv[2]
src_folder = Path(dest_folder).parent

build_profile = dict()
build_profile['_'] = 'Build Profile Generated from Doxygen XML'
build_profile['type'] = 'feature_profile'
build_profile['enabled_classes'] = []
build_profile['enabled_classes'].append("OS")

ClassInfo = namedtuple("ClassInfo", ["class_name", "reference"])

def get_class_name(data_node: et.Element) -> ClassInfo:
    # todo: update docstring for new method signature
    """
    Gets the class name from the doxygen node's id attribute
    :param data_node: The doxygen XML node containing the class data
    :return: a string containing the class name
    """
    class_name = data_node.attrib['id']
    name = class_name.replace("class", "")
    reference_node  = data_node.find('includes')
    reference = reference_node.attrib['refid']
    return ClassInfo(name, reference)


def parse_reference_file(reference):
    file_name = reference + ".xml"
    xml_reference_file = next(Path(xml_input_folder).rglob(file_name), None)
    if xml_reference_file:
        tree = et.parse(xml_reference_file)
        root = tree.getroot()
        data_node = root[0]
        include_node_list = data_node.findall('includes')
        for include_node in include_node_list:
            if include_node.text.startswith('godot_cpp'):
                include_file_name = Path(include_node.text).name.replace('.hpp', '')
                class_name = "".join(word.capitalize() for word in include_file_name.split("_"))
                # handle the fact that 2d or 3d in file name becomes 2D or 3D in Class name
                actual_class_name =  re.sub(r'(?<=\d)(d|D)', lambda match: match.group(0).upper(), class_name)
                if actual_class_name not in build_profile['enabled_classes']:
                    build_profile['enabled_classes'].append(actual_class_name)
    else:
        print("file not found " + file_name)


def create_profile_for_class(file):
    tree = et.parse(file)
    root = tree.getroot()
    data_node = root[0]
    class_info = get_class_name(data_node)
    parse_reference_file(class_info.reference)


def write_output():
    file_name = src_folder / 'build_profile_gen.json'
    with open(file_name, 'w') as f:
        json.dump(build_profile, f,indent=4)


def parse_class_xml_files() -> None:
    """
    loop through the class documentation files generated by doxygen and
    create a Godot class document file for each
    :return: None
    """
    files = list(Path(xml_input_folder).rglob('class*.xml'))
    for file in files:
        create_profile_for_class(file)
        write_output()


parse_class_xml_files()
